version: '3.2'

services:
  replica1_node1:
      container_name: replica1_node1
      image: fauna/faunadb
      volumes:
        - './replica_1/node_1/etc/faunadb.yml:/etc/faunadb.yml'
      expose:
        - "8443"
      command: '--config /etc/faunadb.yml'

  replica1_node2:
      container_name: replica1_node2
      image: fauna/faunadb
      volumes:
        - './replica_1/node_2/etc/faunadb.yml:/etc/faunadb.yml'
      expose:
        - "8443"
      links:
        - replica1_node1
      command: '--config /etc/faunadb.yml --join replica1_node1'
      depends_on:
        - replica1_node1 

  load_balancer:
      container_name: load_balancer
      image: nginx
      volumes:
        - './load_balancer/etc/nginx/nginx.conf:/etc/nginx/nginx.conf'
      links:
          - replica1_node1
          - replica1_node2
      ports:
          - '8080:8080'
      depends_on:
        - replica1_node1
        - replica1_node2